"""Initial database

Revision ID: ec601dc0752a
Revises: 
Create Date: 2018-06-24 00:58:50.588843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec601dc0752a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zm_session',
    sa.Column('_id', sa.String(length=15), nullable=False),
    sa.Column('initial_date', sa.DateTime(), nullable=True),
    sa.Column('conclusion_date', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('bkp_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('zm_user',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('zm_session_id', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('initial_date', sa.DateTime(), nullable=True),
    sa.Column('conclusion_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['zm_session_id'], ['zm_session._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zm_user')
    op.drop_table('zm_session')
    # ### end Alembic commands ###
